name: 'Check Binary Files'
description: 'A GitHub Action to check for binary files in commits'
inputs:
  base-ref:
    description: 'The base reference to compare with'
    required: false
  head-ref:
    description: 'The head reference to compare with'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Run check-binary-files script
      shell: bash
      env:
        BASE: ${{ inputs.base-ref }}
        HEAD: ${{ inputs.head-ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        GITHUB_EVENT_AFTER: ${{ github.event.after }}
        GITHUB_EVENT_PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_EVENT_PULL_REQUEST_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      run: ${GITHUB_ACTION_PATH}/scripts/check_binary_files.sh

