name: 'setup-qemu-static'
description: 'A GitHub Action to install qemu-static related packages and enable targets based on input variables'
inputs:
  targets:
    description: 'A list of targets to enable'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install qemu-static packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static
        sudo apt-get install -y binfmt-support
        sudo apt-get install -y update-binfmts
    - name: Enable targets
      if: ${{ inputs.targets != '' }}
      shell: bash
      run: |
        for target in ${{ inputs.targets }}; do
          sudo update-binfmts --enable $target || sudo update-binfmts --importdir /var/lib/binfmts --import $target
        done
