name: 'Detect Secrets'
description: 'A GitHub Action to run yelp/detect-secrets to scan for secrets in the repository'
inputs:
  baseline-file:
    description: 'The path to the .baseline file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install detect-secrets
      run: |
        python -m pip install detect-secrets
    - name: Run detect-secrets scan
      shell: bash
      run: ${GITHUB_ACTION_PATH}/scan_secrets.sh ${{ inputs.baseline-file }}
