name: Test Setup QEMU Static

on:
  push:
    branches:
      - master
    paths:
      - setup-qemu-static/**
  pull_request:
    branches:
      - master
    paths:
      - setup-qemu-static/**

jobs:
  test-setup-qemu-static:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run setup-qemu-static action
      uses: ./setup-qemu-static
      with:
        targets: 'aarch64 arm'
